name: Build issue 3379 fix

on:
  push:
    branches:
      - fix/issue-3379-sign-text
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: gradle
          java-version: 25
      - name: Build
        run: ./gradlew build -s
      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-Issue-3379
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-*.jar
          if-no-files-found: error
          retention-days: 14
